from __future__ import annotations

import csv

import paths

PACK_CSV = paths.OPENAI_ANTHROPIC_EVIDENCE_PACK_CSV


SERIES = [
    {"period": "2023", "openai_gw": "0.2", "anthropic_gw": "0.08", "estimate_type": "official exact / triangulated center"},
    {"period": "2024", "openai_gw": "0.6", "anthropic_gw": "0.18", "estimate_type": "official exact / triangulated center"},
    {"period": "2025", "openai_gw": "1.9", "anthropic_gw": "1.3", "estimate_type": "official exact / floor-plus-uplift"},
    {"period": "2026 current", "openai_gw": "2.0", "anthropic_gw": "1.6", "estimate_type": "best estimate from layered evidence"},
    {"period": "2026 year-end", "openai_gw": "3.6", "anthropic_gw": "3.3", "estimate_type": "best estimate from layered evidence"},
    {"period": "2027 year-end", "openai_gw": "6.2", "anthropic_gw": "6.0", "estimate_type": "best estimate from layered evidence"},
    {"period": "2028 year-end", "openai_gw": "7.2", "anthropic_gw": "7.0", "estimate_type": "conservative forward estimate"},
    {"period": "2029 year-end", "openai_gw": "9.0", "anthropic_gw": "7.6", "estimate_type": "conservative forward estimate"},
]


EVIDENCE = [
    {
        "evidence_id": "oa_01",
        "company": "OpenAI",
        "years_used": "2023-2025",
        "source_date": "2026-02-12",
        "title": "OpenAI US House Select Committee Update",
        "url": "https://cdn.openai.com/pdf/045aa967-ee96-4a09-94ee-3098ddf6db2c/OpenAI-US-House-Select-Cmte-Update-%5B021226%5D.pdf",
        "source_family": "official_company",
        "independence_class": "primary",
        "evidence_type": "company_total",
        "quant_signal": "0.2 GW in 2023; 0.6 GW in 2024; ~1.9 GW in 2025",
        "role_in_model": "anchor",
        "additivity": "replace_only",
        "overlap_risk": "low",
        "weight": "critical",
        "note": "This is the clean backbone for OpenAI historical years and overrides the weaker local site floor.",
    },
    {
        "evidence_id": "oa_02",
        "company": "OpenAI",
        "years_used": "2024-2029",
        "source_date": "2026-03-27",
        "title": "Epoch AI data centers",
        "url": "https://epoch.ai/data/data-centers",
        "source_family": "external_dataset",
        "independence_class": "reference_dataset",
        "evidence_type": "site_floor",
        "quant_signal": "0.053 GW YE2024; 0.991 GW YE2025/current; 3.137 GW YE2026; 6.106 GW YE2027; 7.226 GW YE2028; 8.99 GW YE2029",
        "role_in_model": "lower_bound",
        "additivity": "site_additive_after_dedup",
        "overlap_risk": "medium",
        "weight": "critical",
        "note": "Epoch AI site registry rolled up into a single-user lower bound for later years.",
    },
    {
        "evidence_id": "oa_03",
        "company": "OpenAI",
        "years_used": "2026",
        "source_date": "2025-11-03",
        "title": "AWS and OpenAI announce multi-year strategic partnership",
        "url": "https://openai.com/index/aws-and-openai-partnership/",
        "source_family": "official_partner_provider",
        "independence_class": "partner_primary",
        "evidence_type": "provider_capacity_commitment",
        "quant_signal": "hundreds of thousands of NVIDIA GPUs; all capacity targeted to deploy before end-2026",
        "role_in_model": "uplift",
        "additivity": "additive_candidate",
        "overlap_risk": "high",
        "weight": "high",
        "note": "Useful as a 2026 ramp signal, but not safe to add one-for-one on top of Stargate umbrella claims.",
    },
    {
        "evidence_id": "oa_04",
        "company": "OpenAI",
        "years_used": "2026-2027",
        "source_date": "2025-09-24",
        "title": "OpenAI, Oracle, and SoftBank expand Stargate with five new AI data center sites",
        "url": "https://group.softbank/en/news/press/20250924",
        "source_family": "official_joint_press",
        "independence_class": "joint_primary",
        "evidence_type": "umbrella_platform_envelope",
        "quant_signal": "nearly 7 GW planned capacity; over 5.5 GW from newly described sites; path to 10 GW commitment",
        "role_in_model": "envelope",
        "additivity": "non_additive_envelope",
        "overlap_risk": "high",
        "weight": "high",
        "note": "Strong directional evidence for scale, but explicitly not additive with sub-site or provider components.",
    },
    {
        "evidence_id": "oa_05",
        "company": "OpenAI",
        "years_used": "2026-2028",
        "source_date": "2025-09-22",
        "title": "OpenAI and NVIDIA announce strategic partnership",
        "url": "https://openai.com/index/openai-nvidia-systems-partnership/",
        "source_family": "official_partner_provider",
        "independence_class": "partner_primary",
        "evidence_type": "hardware_supply_commitment",
        "quant_signal": "10 GW partnership; first 1 GW starts in H2 2026",
        "role_in_model": "uplift",
        "additivity": "additive_candidate",
        "overlap_risk": "high",
        "weight": "medium",
        "note": "Useful timing evidence for 2026, but too overlap-heavy to stack broadly.",
    },
    {
        "evidence_id": "oa_06",
        "company": "OpenAI",
        "years_used": "2026-2028",
        "source_date": "2026-01-08",
        "title": "OpenAI partners with Cerebras",
        "url": "https://openai.com/index/cerebras-partnership/",
        "source_family": "official_partner_provider",
        "independence_class": "partner_primary",
        "evidence_type": "provider_capacity_commitment",
        "quant_signal": "750 MW phased through 2028",
        "role_in_model": "uplift",
        "additivity": "additive_candidate",
        "overlap_risk": "medium",
        "weight": "medium",
        "note": "Phased and partly independent of Stargate campuses, but still not fully additive without utilization timing.",
    },
    {
        "evidence_id": "oa_07",
        "company": "OpenAI",
        "years_used": "2026-2027",
        "source_date": "2025-10-17",
        "title": "OpenAI and SoftBank Group partner with SB Energy",
        "url": "https://openai.com/index/stargate-sb-energy-partnership/",
        "source_family": "official_partner_provider",
        "independence_class": "partner_primary",
        "evidence_type": "site_power_commitment",
        "quant_signal": "1.2 GW initial buildout",
        "role_in_model": "uplift",
        "additivity": "additive_candidate",
        "overlap_risk": "high",
        "weight": "medium",
        "note": "Important as a buildout lane, but likely overlaps with broader Stargate and site-level counts.",
    },
    {
        "evidence_id": "oa_08",
        "company": "OpenAI",
        "years_used": "2027",
        "source_date": "2025-09-18",
        "title": "Inside the world's most powerful AI datacenter",
        "url": "https://blogs.microsoft.com/blog/2025/09/18/inside-the-worlds-most-powerful-ai-datacenter/",
        "source_family": "host_operator",
        "independence_class": "partner_primary",
        "evidence_type": "allocation_guardrail",
        "quant_signal": "Fairwater powers OpenAI, Microsoft AI, Copilot, and other workloads",
        "role_in_model": "guardrail",
        "additivity": "support_only",
        "overlap_risk": "low",
        "weight": "high",
        "note": "Prevents assigning all Fairwater Wisconsin capacity to OpenAI in the single-number series.",
    },
    {
        "evidence_id": "oa_09",
        "company": "OpenAI",
        "years_used": "2026-2029",
        "source_date": "2025-10-27",
        "title": "OpenAI OSTP RFI response",
        "url": "https://cdn.openai.com/pdf/21b88bb5-10a3-4566-919d-f9a6b9c3e632/openai-ostp-rfi-oct-27-2025.pdf",
        "source_family": "official_company",
        "independence_class": "primary",
        "evidence_type": "policy_submission_scale_signal",
        "quant_signal": "already announced capacity brings Stargate to nearly 7 GW planned; references Wisconsin grid-connected capacity",
        "role_in_model": "corroboration",
        "additivity": "support_only",
        "overlap_risk": "high",
        "weight": "medium",
        "note": "Useful as an internal consistency check on the Stargate trajectory rather than a separable MW source.",
    },
    {
        "evidence_id": "oa_10",
        "company": "OpenAI",
        "years_used": "2026-2029",
        "source_date": "2025-11-03",
        "title": "AP: Microsoft takes over part of Crusoe's Abilene data center project",
        "url": "https://apnews.com/article/ai-stargate-microsoft-openai-crusoe-oracle-f4f74c3a4617d8cfab5b933fc31ccc6e",
        "source_family": "independent_media",
        "independence_class": "independent",
        "evidence_type": "orthogonal_capacity_check",
        "quant_signal": "Abilene / Oracle / Microsoft complex expected around 2.1 GW",
        "role_in_model": "orthogonal_check",
        "additivity": "support_only",
        "overlap_risk": "low",
        "weight": "medium",
        "note": "Independent evidence that the OpenAI/Oracle/Crusoe/Microsoft buildout is physically real and already very large.",
    },
    {
        "evidence_id": "oa_11",
        "company": "OpenAI",
        "years_used": "2026-2029",
        "source_date": "2025-06-30",
        "title": "Data Center Dynamics: OpenAI confirmed to be behind Oracle cloud deal",
        "url": "https://www.datacenterdynamics.com/en/news/openai-confirmed-to-be-behind-30bn-a-year-oracle-cloud-deal-45gw-expected-across-multiple-data-center-sites/",
        "source_family": "trade_media",
        "independence_class": "independent",
        "evidence_type": "orthogonal_capacity_check",
        "quant_signal": "about 4.5 GW expected across multiple data center sites",
        "role_in_model": "orthogonal_check",
        "additivity": "support_only",
        "overlap_risk": "medium",
        "weight": "medium",
        "note": "Independent trade-press support that OpenAI's later-year footprint is multi-gigawatt even after de-duplication concerns.",
    },
    {
        "evidence_id": "an_01",
        "company": "Anthropic",
        "years_used": "2023",
        "source_date": "2023-02-03",
        "title": "Anthropic forges partnership with Google Cloud",
        "url": "https://www.prnewswire.com/news-releases/anthropic-forges-partnership-with-google-cloud-to-help-deliver-reliable-and-responsible-ai-301738512.html",
        "source_family": "wire_press_release",
        "independence_class": "partner_primary",
        "evidence_type": "continuity_nonzero",
        "quant_signal": "partnership and cloud access in 2023",
        "role_in_model": "nonzero_proof",
        "additivity": "support_only",
        "overlap_risk": "low",
        "weight": "high",
        "note": "Part of the reason Anthropic cannot be zero in 2023.",
    },
    {
        "evidence_id": "an_02",
        "company": "Anthropic",
        "years_used": "2023-2024",
        "source_date": "2023-11-08",
        "title": "Cloud TPU v5e is generally available",
        "url": "https://cloud.google.com/blog/products/compute/announcing-cloud-tpu-v5e-in-ga",
        "source_family": "official_partner_provider",
        "independence_class": "partner_primary",
        "evidence_type": "continuity_nonzero",
        "quant_signal": "Anthropic already using TPU v5e to scale Claude serving",
        "role_in_model": "nonzero_proof",
        "additivity": "support_only",
        "overlap_risk": "low",
        "weight": "high",
        "note": "Strong proof that Anthropic had meaningful Google-side compute before the site tracker saw it.",
    },
    {
        "evidence_id": "an_03",
        "company": "Anthropic",
        "years_used": "2023-2024",
        "source_date": "2024-11-19",
        "title": "CMA full text decision on Google / Anthropic",
        "url": "https://assets.publishing.service.gov.uk/media/676959bae6ff7c8a1fde9d33/Full_text_decision__.pdf",
        "source_family": "regulatory",
        "independence_class": "independent",
        "evidence_type": "regulatory_continuity",
        "quant_signal": "Anthropic sourced compute from Google and Amazon in 2023",
        "role_in_model": "nonzero_proof",
        "additivity": "support_only",
        "overlap_risk": "low",
        "weight": "high",
        "note": "Important orthogonal proof that Anthropic had multi-cloud compute before the visible floor turns on.",
    },
    {
        "evidence_id": "an_04",
        "company": "Anthropic",
        "years_used": "2024-2025",
        "source_date": "2024-11-22",
        "title": "Powering the next generation of AI development with AWS",
        "url": "https://www.anthropic.com/news/anthropic-amazon-trainium",
        "source_family": "official_company",
        "independence_class": "primary",
        "evidence_type": "platform_anchor",
        "quant_signal": "AWS as primary training partner; Project Rainier positioning",
        "role_in_model": "anchor",
        "additivity": "support_only",
        "overlap_risk": "medium",
        "weight": "high",
        "note": "Defines AWS as the primary Anthropic training lane heading into 2025.",
    },
    {
        "evidence_id": "an_05",
        "company": "Anthropic",
        "years_used": "2024-2025",
        "source_date": "2024-12-03",
        "title": "Claude 3.5 Haiku on AWS Trainium2 and model distillation",
        "url": "https://www.anthropic.com/news/trainium2-and-distillation",
        "source_family": "official_company",
        "independence_class": "primary",
        "evidence_type": "quantitative_platform_anchor",
        "quant_signal": "hundreds of thousands of Trainium2 chips; >5x current-generation compute",
        "role_in_model": "anchor",
        "additivity": "support_only",
        "overlap_risk": "medium",
        "weight": "high",
        "note": "Crucial quantitative anchor that rules out tiny 2024 Anthropic numbers.",
    },
    {
        "evidence_id": "an_06",
        "company": "Anthropic",
        "years_used": "2025-2026",
        "source_date": "2025-11-03",
        "title": "AWS activates Project Rainier",
        "url": "https://www.aboutamazon.com/news/aws/aws-project-rainier-ai-trainium-chips-compute-cluster",
        "source_family": "official_partner_provider",
        "independence_class": "partner_primary",
        "evidence_type": "platform_capacity",
        "quant_signal": "nearly 500,000 live chips and >1 million by end-2025",
        "role_in_model": "anchor",
        "additivity": "support_only",
        "overlap_risk": "medium",
        "weight": "critical",
        "note": "Best hard AWS-side Anthropic scale anchor.",
    },
    {
        "evidence_id": "an_07",
        "company": "Anthropic",
        "years_used": "2026",
        "source_date": "2025-10-23",
        "title": "Expanding our use of Google Cloud TPUs and Services",
        "url": "https://www.anthropic.com/news/expanding-our-use-of-google-cloud-tpus-and-services",
        "source_family": "official_company",
        "independence_class": "primary",
        "evidence_type": "platform_capacity",
        "quant_signal": "up to 1 million TPUs and well over 1 GW online in 2026",
        "role_in_model": "anchor",
        "additivity": "additive_candidate",
        "overlap_risk": "medium",
        "weight": "critical",
        "note": "Best direct Anthropic anchor for moving above the AWS-heavy visible floor in 2026.",
    },
    {
        "evidence_id": "an_08",
        "company": "Anthropic",
        "years_used": "2027-2028",
        "source_date": "2025-07-21",
        "title": "Build AI in America",
        "url": "https://www.anthropic.com/news/build-ai-in-america",
        "source_family": "official_company",
        "independence_class": "primary",
        "evidence_type": "future_anchor",
        "quant_signal": "2 GW data centers for a single training run in 2027 and 5 GW in 2028",
        "role_in_model": "anchor",
        "additivity": "support_only",
        "overlap_risk": "low",
        "weight": "critical",
        "note": "This is the strongest late-year Anthropic anchor and prevents the series from falling back to the floor in 2028.",
    },
    {
        "evidence_id": "an_09",
        "company": "Anthropic",
        "years_used": "2027-2029",
        "source_date": "2025-12-17",
        "title": "Hut 8 Announces AI Infrastructure Partnership with Anthropic and Fluidstack",
        "url": "https://www.hut8.com/news-insights/press-releases/hut-8-announces-ai-infrastructure-partnership-with-anthropic-and-fluidstack",
        "source_family": "host_operator",
        "independence_class": "partner_primary",
        "evidence_type": "site_capacity",
        "quant_signal": "245 MW initial River Bend tranche, up to 2,295 MW broader pipeline",
        "role_in_model": "uplift",
        "additivity": "additive_candidate",
        "overlap_risk": "medium",
        "weight": "high",
        "note": "Supports further Anthropic growth beyond the 2027 floor.",
    },
    {
        "evidence_id": "an_10",
        "company": "Anthropic",
        "years_used": "2026-2029",
        "source_date": "2025-11-18",
        "title": "Microsoft, NVIDIA and Anthropic announce strategic partnerships",
        "url": "https://blogs.microsoft.com/blog/2025/11/18/microsoft-nvidia-and-anthropic-announce-strategic-partnerships/",
        "source_family": "official_joint_press",
        "independence_class": "joint_primary",
        "evidence_type": "provider_capacity_commitment",
        "quant_signal": "up to 1 GW additional Azure/NVIDIA capacity",
        "role_in_model": "uplift",
        "additivity": "additive_candidate",
        "overlap_risk": "high",
        "weight": "medium",
        "note": "Important upside lane, but too overlap-sensitive to count fully in 2026 or 2027.",
    },
    {
        "evidence_id": "an_11",
        "company": "Anthropic",
        "years_used": "2026",
        "source_date": "2025-10-23",
        "title": "AP: Anthropic inks multibillion-dollar deal with Google for AI chips",
        "url": "https://apnews.com/article/275df9e291bbb361962dfc6ba868506c",
        "source_family": "independent_media",
        "independence_class": "independent",
        "evidence_type": "orthogonal_capacity_check",
        "quant_signal": "up to 1 million TPUs and well over 1 GW in 2026",
        "role_in_model": "orthogonal_check",
        "additivity": "support_only",
        "overlap_risk": "low",
        "weight": "medium",
        "note": "Independent media corroboration of the official Google TPU announcement.",
    },
    {
        "evidence_id": "an_12",
        "company": "Anthropic",
        "years_used": "2027-2029",
        "source_date": "2025-12-17",
        "title": "Data Center Dynamics: Hut 8 signs 245MW capacity deal with Fluidstack",
        "url": "https://www.datacenterdynamics.com/en/news/hut-8-signs-245mw-capacity-deal-with-fluidstack-as-part-of-multi-gigawatt-partnership-with-anthropic/",
        "source_family": "trade_media",
        "independence_class": "independent",
        "evidence_type": "orthogonal_site_check",
        "quant_signal": "245 MW initial River Bend capacity with optional additional capacity",
        "role_in_model": "orthogonal_check",
        "additivity": "support_only",
        "overlap_risk": "low",
        "weight": "medium",
        "note": "Independent trade-press corroboration that the River Bend lane is real and non-trivial.",
    },
    {
        "evidence_id": "an_13",
        "company": "Anthropic",
        "years_used": "2027-2029",
        "source_date": "2026-04-06",
        "title": "Anthropic expands partnership with Google and Broadcom for multiple gigawatts of next-generation compute",
        "url": "https://www.anthropic.com/news/google-broadcom-partnership-compute",
        "source_family": "official_company",
        "independence_class": "primary",
        "evidence_type": "future_platform_capacity",
        "quant_signal": "multiple gigawatts of next-generation TPU capacity starting in 2027",
        "role_in_model": "anchor",
        "additivity": "additive_candidate",
        "overlap_risk": "medium",
        "weight": "critical",
        "note": "New direct Anthropic evidence that the Google lane expands materially again from 2027 onward; it strengthens the projected ramp more than the March 2026 current point.",
    },
    {
        "evidence_id": "sh_01",
        "company": "Shared",
        "years_used": "2026-2029",
        "source_date": "2025-08-28",
        "title": "SemiAnalysis Datacenter Industry Model",
        "url": "https://newsletter.semianalysis.com/p/datacenter-model",
        "source_family": "third_party_model",
        "independence_class": "independent",
        "evidence_type": "industry_cross_check",
        "quant_signal": "tracks datacenter capacity by hyperscaler, AI lab, site, and region",
        "role_in_model": "orthogonal_check",
        "additivity": "support_only",
        "overlap_risk": "medium",
        "weight": "low",
        "note": "Shared cross-check for both companies; not used as a numeric anchor.",
    },
]


def write_csv(path: Path, rows: list[dict[str, str]]) -> None:
    fieldnames = list(rows[0].keys())
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, quoting=csv.QUOTE_MINIMAL)
        writer.writeheader()
        writer.writerows(rows)


def build_methodology_md() -> str:
    lines = [
        "# OpenAI / Anthropic Methodology Memo",
        "",
        "## Objective",
        "",
        "Estimate the best public year-by-year view of OpenAI and Anthropic compute capacity in `GW`, using a consistent non-overlapping logic.",
        "",
        "## What These Numbers Mean",
        "",
        "- The figures are **best estimates of company-accessible AI datacenter compute capacity in gigawatts**, not instantaneous live power draw.",
        "- They mix training and serving capacity where the public evidence does the same.",
        "- They are **not** chip-normalized and are **not** H100-equivalents.",
        "",
        "## Evidence Hierarchy",
        "",
        "1. `Tier 1`: direct official company totals",
        "2. `Tier 2`: official site or provider quantitative disclosures",
        "3. `Tier 3`: host/operator infrastructure disclosures",
        "4. `Tier 4`: regulatory and continuity evidence proving nonzero or multi-cloud usage",
        "5. `Tier 5`: independent media and third-party model cross-checks",
        "",
        "## Core Rules",
        "",
        "- Start from official company totals when they exist. This is why OpenAI `2023-2025` comes directly from the House update.",
        "- Otherwise start from the **site-backed floor** built from named datacenters and primary-user allocation.",
        "- Only add uplift when there is a defensible reason it is incremental and likely online by the relevant date.",
        "- Do **not** sum umbrella claims with subcomponents. Examples: Stargate, NVIDIA, AMD, Broadcom, Azure, Google TPU, and AWS Trainium commitments often overlap.",
        "- Use host/operator and regulatory evidence as guardrails, not standalone totals.",
        "- Keep the series economically and physically plausible. A best-estimate series should not fall below the prior-year best estimate without specific contrary evidence.",
        "",
        "## Current Best-Estimate Series",
        "",
        "| Period | OpenAI | Anthropic |",
        "| --- | ---: | ---: |",
    ]
    for row in SERIES:
        lines.append(f"| {row['period']} | `{row['openai_gw']} GW` | `{row['anthropic_gw']} GW` |")
    lines += [
        "",
        "## How To Read The Two Companies",
        "",
        "- `OpenAI 2023-2025`: mostly official company-reported compute.",
        "- `OpenAI 2026+`: named-site floor plus conservative provider/buildout uplift, with heavy de-duplication around Stargate-style umbrella announcements.",
        "- `Anthropic 2023-2024`: triangulated from continuity, regulatory, and early platform evidence.",
        "- `Anthropic 2025+`: named-site floor plus AWS and Google platform evidence, then future-year anchors from Anthropic's own infrastructure statements.",
        "",
        "## Orthogonal Checks Added In This Round",
        "",
        "- Regulatory evidence: CMA decision on Google / Anthropic.",
        "- Host/operator evidence: Microsoft Fairwater blog, Hut 8 River Bend press release.",
        "- Independent media: AP on Anthropic / Google TPU deal, Data Center Dynamics on River Bend.",
        "- Third-party model: SemiAnalysis Datacenter Industry Model.",
        "",
        "## Main Weaknesses",
        "",
        "- Anthropic still does not disclose one clean company-total series in `GW` the way OpenAI does for `2023-2025`.",
        "- OpenAI `2027+` remains sensitive to how much shared Microsoft/Fairwater capacity should be attributed to OpenAI specifically.",
        "- Forward years remain more overlap-sensitive than historical years, even after de-duplication.",
    ]
    return "\n".join(lines) + "\n"


def build_pack_md(rows: list[dict[str, str]]) -> str:
    by_company: dict[str, list[dict[str, str]]] = {}
    for row in rows:
        by_company.setdefault(row["company"], []).append(row)

    lines = [
        "# OpenAI / Anthropic Evidence Pack",
        "",
        "This pack lists the evidence used to build the year-by-year GW estimates and explicitly tags each item by role: `anchor`, `lower_bound`, `uplift`, `guardrail`, or `orthogonal_check`.",
        "",
        "## Summary",
        "",
        f"- Total evidence items: `{len(rows)}`",
        f"- OpenAI items: `{len(by_company.get('OpenAI', []))}`",
        f"- Anthropic items: `{len(by_company.get('Anthropic', []))}`",
        f"- Shared cross-check items: `{len(by_company.get('Shared', []))}`",
        "",
    ]

    for company in ("OpenAI", "Anthropic", "Shared"):
        lines += [
            f"## {company}",
            "",
            "| ID | Years | Date | Source | Family | Role | Additivity | Overlap | Quant signal | Note |",
            "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
        for row in by_company[company]:
            lines.append(
                f"| {row['evidence_id']} | {row['years_used']} | {row['source_date']} | "
                f"[{row['title']}]({row['url']}) | {row['source_family']} | {row['role_in_model']} | "
                f"{row['additivity']} | {row['overlap_risk']} | {row['quant_signal']} | {row['note']} |"
            )
        lines.append("")

    lines += [
        "## How To Use This Pack",
        "",
        "- `anchor`: can directly set or strongly center the estimate.",
        "- `lower_bound`: hard floor, usually from confirmed named sites.",
        "- `uplift`: can move the estimate above the floor if timing and overlap are handled carefully.",
        "- `guardrail`: prevents an over-attribution or implausible interpretation.",
        "- `orthogonal_check`: independent corroboration used to see if the series makes sense, not to define it by itself.",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    paths.DERIVED_DIR.mkdir(parents=True, exist_ok=True)
    write_csv(PACK_CSV, EVIDENCE)
    print(f"Wrote {PACK_CSV}")


if __name__ == "__main__":
    main()
